// ISO 3661-1 alpha-2
// https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
export const iso36611Alpha2 = [
	"AF",
	"AL",
	"DZ",
	"AS",
	"AD",
	"AO",
	"AI",
	"AQ",
	"AG",
	"AR",
	"AM",
	"AW",
	"AU",
	"AT",
	"AZ",
	"BS",
	"BH",
	"BD",
	"BB",
	"BY",
	"BE",
	"BZ",
	"BJ",
	"BM",
	"BT",
	"BO",
	"BQ",
	"BA",
	"BW",
	"BV",
	"BR",
	"IO",
	"BN",
	"BG",
	"BF",
	"BI",
	"CV",
	"KH",
	"CM",
	"CA",
	"KY",
	"CF",
	"TD",
	"CL",
	"CN",
	"CX",
	"CC",
	"CO",
	"KM",
	"CD",
	"CG",
	"CK",
	"CR",
	"HR",
	"CU",
	"CW",
	"CY",
	"CZ",
	"CI",
	"DK",
	"DJ",
	"DM",
	"DO",
	"EC",
	"EG",
	"SV",
	"GQ",
	"ER",
	"EE",
	"SZ",
	"ET",
	"FK",
	"FO",
	"FJ",
	"FI",
	"FR",
	"GF",
	"PF",
	"TF",
	"GA",
	"GM",
	"GE",
	"DE",
	"GH",
	"GI",
	"GR",
	"GL",
	"GD",
	"GP",
	"GU",
	"GT",
	"GG",
	"GN",
	"GW",
	"GY",
	"HT",
	"HM",
	"VA",
	"HN",
	"HK",
	"HU",
	"IS",
	"IN",
	"ID",
	"IR",
	"IQ",
	"IE",
	"IM",
	"IL",
	"IT",
	"JM",
	"JP",
	"JE",
	"JO",
	"KZ",
	"KE",
	"KI",
	"KP",
	"KR",
	"KW",
	"KG",
	"LA",
	"LV",
	"LB",
	"LS",
	"LR",
	"LY",
	"LI",
	"LT",
	"LU",
	"MO",
	"MG",
	"MW",
	"MY",
	"MV",
	"ML",
	"MT",
	"MH",
	"MQ",
	"MR",
	"MU",
	"YT",
	"MX",
	"FM",
	"MD",
	"MC",
	"MN",
	"ME",
	"MS",
	"MA",
	"MZ",
	"MM",
	"NA",
	"NR",
	"NP",
	"NL",
	"NC",
	"NZ",
	"NI",
	"NE",
	"NG",
	"NU",
	"NF",
	"MK",
	"MP",
	"NO",
	"OM",
	"PK",
	"PW",
	"PS",
	"PA",
	"PG",
	"PY",
	"PE",
	"PH",
	"PN",
	"PL",
	"PT",
	"PR",
	"QA",
	"RO",
	"RU",
	"RW",
	"RE",
	"BL",
	"SH",
	"KN",
	"LC",
	"MF",
	"PM",
	"VC",
	"WS",
	"SM",
	"ST",
	"SA",
	"SN",
	"RS",
	"SC",
	"SL",
	"SG",
	"SX",
	"SK",
	"SI",
	"SB",
	"SO",
	"ZA",
	"GS",
	"SS",
	"ES",
	"LK",
	"SD",
	"SR",
	"SJ",
	"SE",
	"CH",
	"SY",
	"TW",
	"TJ",
	"TZ",
	"TH",
	"TL",
	"TG",
	"TK",
	"TO",
	"TT",
	"TN",
	"TM",
	"TC",
	"TV",
	"TR",
	"UG",
	"UA",
	"AE",
	"GB",
	"UM",
	"US",
	"UY",
	"UZ",
	"VU",
	"VE",
	"VN",
	"VG",
	"VI",
	"WF",
	"EH",
	"YE",
	"ZM",
	"ZW",
	"AX",
] as const;

export type iso36611Alpha2 = (typeof iso36611Alpha2)[number];

export const iso36611Alpha2Map = {
	AF: { displayName: "Afghanistan" },
	AL: { displayName: "Albania" },
	DZ: { displayName: "Algeria" },
	AS: { displayName: "American Samoa" },
	AD: { displayName: "Andorra" },
	AO: { displayName: "Angola" },
	AI: { displayName: "Anguilla" },
	AQ: { displayName: "Antarctica" },
	AG: { displayName: "Antigua and Barbuda" },
	AR: { displayName: "Argentina" },
	AM: { displayName: "Armenia" },
	AW: { displayName: "Aruba" },
	AU: { displayName: "Australia" },
	AT: { displayName: "Austria" },
	AZ: { displayName: "Azerbaijan" },
	BS: { displayName: "Bahamas (the)" },
	BH: { displayName: "Bahrain" },
	BD: { displayName: "Bangladesh" },
	BB: { displayName: "Barbados" },
	BY: { displayName: "Belarus" },
	BE: { displayName: "Belgium" },
	BZ: { displayName: "Belize" },
	BJ: { displayName: "Benin" },
	BM: { displayName: "Bermuda" },
	BT: { displayName: "Bhutan" },
	BO: { displayName: "Bolivia (Plurinational State of)" },
	BQ: { displayName: "Bonaire, Sint Eustatius and Saba" },
	BA: { displayName: "Bosnia and Herzegovina" },
	BW: { displayName: "Botswana" },
	BV: { displayName: "Bouvet Island" },
	BR: { displayName: "Brazil" },
	IO: { displayName: "British Indian Ocean Territory (the)" },
	BN: { displayName: "Brunei Darussalam" },
	BG: { displayName: "Bulgaria" },
	BF: { displayName: "Burkina Faso" },
	BI: { displayName: "Burundi" },
	CV: { displayName: "Cabo Verde" },
	KH: { displayName: "Cambodia" },
	CM: { displayName: "Cameroon" },
	CA: { displayName: "Canada" },
	KY: { displayName: "Cayman Islands (the)" },
	CF: { displayName: "Central African Republic (the)" },
	TD: { displayName: "Chad" },
	CL: { displayName: "Chile" },
	CN: { displayName: "China" },
	CX: { displayName: "Christmas Island" },
	CC: { displayName: "Cocos (Keeling) Islands (the)" },
	CO: { displayName: "Colombia" },
	KM: { displayName: "Comoros (the)" },
	CD: { displayName: "Congo (the Democratic Republic of the)" },
	CG: { displayName: "Congo (the)" },
	CK: { displayName: "Cook Islands (the)" },
	CR: { displayName: "Costa Rica" },
	HR: { displayName: "Croatia" },
	CU: { displayName: "Cuba" },
	CW: { displayName: "Curaçao" },
	CY: { displayName: "Cyprus" },
	CZ: { displayName: "Czechia" },
	CI: { displayName: "Côte d'Ivoire" },
	DK: { displayName: "Denmark" },
	DJ: { displayName: "Djibouti" },
	DM: { displayName: "Dominica" },
	DO: { displayName: "Dominican Republic (the)" },
	EC: { displayName: "Ecuador" },
	EG: { displayName: "Egypt" },
	SV: { displayName: "El Salvador" },
	GQ: { displayName: "Equatorial Guinea" },
	ER: { displayName: "Eritrea" },
	EE: { displayName: "Estonia" },
	SZ: { displayName: "Eswatini" },
	ET: { displayName: "Ethiopia" },
	FK: { displayName: "Falkland Islands (the) [Malvinas]" },
	FO: { displayName: "Faroe Islands (the)" },
	FJ: { displayName: "Fiji" },
	FI: { displayName: "Finland" },
	FR: { displayName: "France" },
	GF: { displayName: "French Guiana" },
	PF: { displayName: "French Polynesia" },
	TF: { displayName: "French Southern Territories (the)" },
	GA: { displayName: "Gabon" },
	GM: { displayName: "Gambia (the)" },
	GE: { displayName: "Georgia" },
	DE: { displayName: "Germany" },
	GH: { displayName: "Ghana" },
	GI: { displayName: "Gibraltar" },
	GR: { displayName: "Greece" },
	GL: { displayName: "Greenland" },
	GD: { displayName: "Grenada" },
	GP: { displayName: "Guadeloupe" },
	GU: { displayName: "Guam" },
	GT: { displayName: "Guatemala" },
	GG: { displayName: "Guernsey" },
	GN: { displayName: "Guinea" },
	GW: { displayName: "Guinea-Bissau" },
	GY: { displayName: "Guyana" },
	HT: { displayName: "Haiti" },
	HM: { displayName: "Heard Island and McDonald Islands" },
	VA: { displayName: "Holy See (the)" },
	HN: { displayName: "Honduras" },
	HK: { displayName: "Hong Kong" },
	HU: { displayName: "Hungary" },
	IS: { displayName: "Iceland" },
	IN: { displayName: "India" },
	ID: { displayName: "Indonesia" },
	IR: { displayName: "Iran (Islamic Republic of)" },
	IQ: { displayName: "Iraq" },
	IE: { displayName: "Ireland" },
	IM: { displayName: "Isle of Man" },
	IL: { displayName: "Israel" },
	IT: { displayName: "Italy" },
	JM: { displayName: "Jamaica" },
	JP: { displayName: "Japan" },
	JE: { displayName: "Jersey" },
	JO: { displayName: "Jordan" },
	KZ: { displayName: "Kazakhstan" },
	KE: { displayName: "Kenya" },
	KI: { displayName: "Kiribati" },
	KP: { displayName: "Korea (the Democratic People's Republic of)" },
	KR: { displayName: "Korea (the Republic of)" },
	KW: { displayName: "Kuwait" },
	KG: { displayName: "Kyrgyzstan" },
	LA: { displayName: "Lao People's Democratic Republic (the)" },
	LV: { displayName: "Latvia" },
	LB: { displayName: "Lebanon" },
	LS: { displayName: "Lesotho" },
	LR: { displayName: "Liberia" },
	LY: { displayName: "Libya" },
	LI: { displayName: "Liechtenstein" },
	LT: { displayName: "Lithuania" },
	LU: { displayName: "Luxembourg" },
	MO: { displayName: "Macao" },
	MG: { displayName: "Madagascar" },
	MW: { displayName: "Malawi" },
	MY: { displayName: "Malaysia" },
	MV: { displayName: "Maldives" },
	ML: { displayName: "Mali" },
	MT: { displayName: "Malta" },
	MH: { displayName: "Marshall Islands (the)" },
	MQ: { displayName: "Martinique" },
	MR: { displayName: "Mauritania" },
	MU: { displayName: "Mauritius" },
	YT: { displayName: "Mayotte" },
	MX: { displayName: "Mexico" },
	FM: { displayName: "Micronesia (Federated States of)" },
	MD: { displayName: "Moldova (the Republic of)" },
	MC: { displayName: "Monaco" },
	MN: { displayName: "Mongolia" },
	ME: { displayName: "Montenegro" },
	MS: { displayName: "Montserrat" },
	MA: { displayName: "Morocco" },
	MZ: { displayName: "Mozambique" },
	MM: { displayName: "Myanmar" },
	NA: { displayName: "Namibia" },
	NR: { displayName: "Nauru" },
	NP: { displayName: "Nepal" },
	NL: { displayName: "Netherlands (the)" },
	NC: { displayName: "New Caledonia" },
	NZ: { displayName: "New Zealand" },
	NI: { displayName: "Nicaragua" },
	NE: { displayName: "Niger (the)" },
	NG: { displayName: "Nigeria" },
	NU: { displayName: "Niue" },
	NF: { displayName: "Norfolk Island" },
	MK: { displayName: "North Macedonia" },
	MP: { displayName: "Northern Mariana Islands (the)" },
	NO: { displayName: "Norway" },
	OM: { displayName: "Oman" },
	PK: { displayName: "Pakistan" },
	PW: { displayName: "Palau" },
	PS: { displayName: "Palestine, State of" },
	PA: { displayName: "Panama" },
	PG: { displayName: "Papua New Guinea" },
	PY: { displayName: "Paraguay" },
	PE: { displayName: "Peru" },
	PH: { displayName: "Philippines (the)" },
	PN: { displayName: "Pitcairn" },
	PL: { displayName: "Poland" },
	PT: { displayName: "Portugal" },
	PR: { displayName: "Puerto Rico" },
	QA: { displayName: "Qatar" },
	RO: { displayName: "Romania" },
	RU: { displayName: "Russian Federation (the)" },
	RW: { displayName: "Rwanda" },
	RE: { displayName: "Réunion" },
	BL: { displayName: "Saint Barthélemy" },
	SH: { displayName: "Saint Helena, Ascension and Tristan da Cunha" },
	KN: { displayName: "Saint Kitts and Nevis" },
	LC: { displayName: "Saint Lucia" },
	MF: { displayName: "Saint Martin (French part)" },
	PM: { displayName: "Saint Pierre and Miquelon" },
	VC: { displayName: "Saint Vincent and the Grenadines" },
	WS: { displayName: "Samoa" },
	SM: { displayName: "San Marino" },
	ST: { displayName: "Sao Tome and Principe" },
	SA: { displayName: "Saudi Arabia" },
	SN: { displayName: "Senegal" },
	RS: { displayName: "Serbia" },
	SC: { displayName: "Seychelles" },
	SL: { displayName: "Sierra Leone" },
	SG: { displayName: "Singapore" },
	SX: { displayName: "Sint Maarten (Dutch part)" },
	SK: { displayName: "Slovakia" },
	SI: { displayName: "Slovenia" },
	SB: { displayName: "Solomon Islands" },
	SO: { displayName: "Somalia" },
	ZA: { displayName: "South Africa" },
	GS: { displayName: "South Georgia and the South Sandwich Islands" },
	SS: { displayName: "South Sudan" },
	ES: { displayName: "Spain" },
	LK: { displayName: "Sri Lanka" },
	SD: { displayName: "Sudan (the)" },
	SR: { displayName: "Suriname" },
	SJ: { displayName: "Svalbard and Jan Mayen" },
	SE: { displayName: "Sweden" },
	CH: { displayName: "Switzerland" },
	SY: { displayName: "Syrian Arab Republic (the)" },
	TW: { displayName: "Taiwan (Province of China)" },
	TJ: { displayName: "Tajikistan" },
	TZ: { displayName: "Tanzania, the United Republic of" },
	TH: { displayName: "Thailand" },
	TL: { displayName: "Timor-Leste" },
	TG: { displayName: "Togo" },
	TK: { displayName: "Tokelau" },
	TO: { displayName: "Tonga" },
	TT: { displayName: "Trinidad and Tobago" },
	TN: { displayName: "Tunisia" },
	TM: { displayName: "Turkmenistan" },
	TC: { displayName: "Turks and Caicos Islands (the)" },
	TV: { displayName: "Tuvalu" },
	TR: { displayName: "Türkiye" },
	UG: { displayName: "Uganda" },
	UA: { displayName: "Ukraine" },
	AE: { displayName: "United Arab Emirates (the)" },
	GB: {
		displayName: "United Kingdom of Great Britain and Northern Ireland (the)",
	},
	UM: { displayName: "United States Minor Outlying Islands (the)" },
	US: { displayName: "United States of America (the)" },
	UY: { displayName: "Uruguay" },
	UZ: { displayName: "Uzbekistan" },
	VU: { displayName: "Vanuatu" },
	VE: { displayName: "Venezuela (Bolivarian Republic of)" },
	VN: { displayName: "Viet Nam" },
	VG: { displayName: "Virgin Islands (British)" },
	VI: { displayName: "Virgin Islands (U.S.)" },
	WF: { displayName: "Wallis and Futuna" },
	EH: { displayName: "Western Sahara*" },
	YE: { displayName: "Yemen" },
	ZM: { displayName: "Zambia" },
	ZW: { displayName: "Zimbabwe" },
	AX: { displayName: "Åland Islands" },
} as const satisfies Record<iso36611Alpha2, { displayName: string }>;

type Country = {
	id: string;
	value: string;
	continent: string;
	label: string;
};

export const countries = [
	{ id: "af", value: "afghanistan", label: "Afghanistan", continent: "Asia" },
	{ id: "al", value: "albania", label: "Albania", continent: "Europe" },
	{ id: "dz", value: "algeria", label: "Algeria", continent: "Africa" },
	{ id: "ad", value: "andorra", label: "Andorra", continent: "Europe" },
	{ id: "ao", value: "angola", label: "Angola", continent: "Africa" },
	{
		id: "ar",
		value: "argentina",
		label: "Argentina",
		continent: "South America",
	},
	{ id: "am", value: "armenia", label: "Armenia", continent: "Asia" },
	{ id: "au", value: "australia", label: "Australia", continent: "Oceania" },
	{ id: "at", value: "austria", label: "Austria", continent: "Europe" },
	{ id: "az", value: "azerbaijan", label: "Azerbaijan", continent: "Asia" },
	{
		id: "bs",
		value: "bahamas",
		label: "Bahamas",
		continent: "North America",
	},
	{ id: "bh", value: "bahrain", label: "Bahrain", continent: "Asia" },
	{ id: "bd", value: "bangladesh", label: "Bangladesh", continent: "Asia" },
	{
		id: "bb",
		value: "barbados",
		label: "Barbados",
		continent: "North America",
	},
	{ id: "by", value: "belarus", label: "Belarus", continent: "Europe" },
	{ id: "be", value: "belgium", label: "Belgium", continent: "Europe" },
	{ id: "bz", value: "belize", label: "Belize", continent: "North America" },
	{ id: "bj", value: "benin", label: "Benin", continent: "Africa" },
	{ id: "bt", value: "bhutan", label: "Bhutan", continent: "Asia" },
	{
		id: "bo",
		value: "bolivia",
		label: "Bolivia",
		continent: "South America",
	},
	{
		id: "ba",
		value: "bosnia-and-herzegovina",
		label: "Bosnia and Herzegovina",
		continent: "Europe",
	},
	{ id: "bw", value: "botswana", label: "Botswana", continent: "Africa" },
	{ id: "br", value: "brazil", label: "Brazil", continent: "South America" },
	{ id: "bn", value: "brunei", label: "Brunei", continent: "Asia" },
	{ id: "bg", value: "bulgaria", label: "Bulgaria", continent: "Europe" },
	{
		id: "bf",
		value: "burkina-faso",
		label: "Burkina Faso",
		continent: "Africa",
	},
	{ id: "bi", value: "burundi", label: "Burundi", continent: "Africa" },
	{ id: "kh", value: "cambodia", label: "Cambodia", continent: "Asia" },
	{ id: "cm", value: "cameroon", label: "Cameroon", continent: "Africa" },
	{ id: "ca", value: "canada", label: "Canada", continent: "North America" },
	{ id: "cv", value: "cape-verde", label: "Cape Verde", continent: "Africa" },
	{
		id: "cf",
		value: "central-african-republic",
		label: "Central African Republic",
		continent: "Africa",
	},
	{ id: "td", value: "chad", label: "Chad", continent: "Africa" },
	{ id: "cl", value: "chile", label: "Chile", continent: "South America" },
	{ id: "cn", value: "china", label: "China", continent: "Asia" },
	{
		id: "co",
		value: "colombia",
		label: "Colombia",
		continent: "South America",
	},
	{ id: "km", value: "comoros", label: "Comoros", continent: "Africa" },
	{ id: "cg", value: "congo", label: "Congo", continent: "Africa" },
	{
		id: "cr",
		value: "costa-rica",
		label: "Costa Rica",
		continent: "North America",
	},
	{ id: "hr", value: "croatia", label: "Croatia", continent: "Europe" },
	{ id: "cu", value: "cuba", label: "Cuba", continent: "North America" },
	{ id: "cy", value: "cyprus", label: "Cyprus", continent: "Asia" },
	{
		id: "cz",
		value: "czech-republic",
		label: "Czech Republic",
		continent: "Europe",
	},
	{ id: "dk", value: "denmark", label: "Denmark", continent: "Europe" },
	{ id: "dj", value: "djibouti", label: "Djibouti", continent: "Africa" },
	{
		id: "dm",
		value: "dominica",
		label: "Dominica",
		continent: "North America",
	},
	{
		id: "do",
		value: "dominican-republic",
		label: "Dominican Republic",
		continent: "North America",
	},
	{
		id: "ec",
		value: "ecuador",
		label: "Ecuador",
		continent: "South America",
	},
	{ id: "eg", value: "egypt", label: "Egypt", continent: "Africa" },
	{
		id: "sv",
		value: "el-salvador",
		label: "El Salvador",
		continent: "North America",
	},
	{
		id: "gq",
		value: "equatorial-guinea",
		label: "Equatorial Guinea",
		continent: "Africa",
	},
	{ id: "er", value: "eritrea", label: "Eritrea", continent: "Africa" },
	{ id: "ee", value: "estonia", label: "Estonia", continent: "Europe" },
	{ id: "et", value: "ethiopia", label: "Ethiopia", continent: "Africa" },
	{ id: "fj", value: "fiji", label: "Fiji", continent: "Oceania" },
	{ id: "fi", value: "finland", label: "Finland", continent: "Europe" },
	{ id: "fr", value: "france", label: "France", continent: "Europe" },
	{ id: "ga", value: "gabon", label: "Gabon", continent: "Africa" },
	{ id: "gm", value: "gambia", label: "Gambia", continent: "Africa" },
	{ id: "ge", value: "georgia", label: "Georgia", continent: "Asia" },
	{ id: "de", value: "germany", label: "Germany", continent: "Europe" },
	{ id: "gh", value: "ghana", label: "Ghana", continent: "Africa" },
	{ id: "gr", value: "greece", label: "Greece", continent: "Europe" },
	{
		id: "gd",
		value: "grenada",
		label: "Grenada",
		continent: "North America",
	},
	{
		id: "gt",
		value: "guatemala",
		label: "Guatemala",
		continent: "North America",
	},
	{ id: "gn", value: "guinea", label: "Guinea", continent: "Africa" },
	{
		id: "gw",
		value: "guinea-bissau",
		label: "Guinea-Bissau",
		continent: "Africa",
	},
	{ id: "gy", value: "guyana", label: "Guyana", continent: "South America" },
	{ id: "ht", value: "haiti", label: "Haiti", continent: "North America" },
	{
		id: "hn",
		value: "honduras",
		label: "Honduras",
		continent: "North America",
	},
	{ id: "hu", value: "hungary", label: "Hungary", continent: "Europe" },
	{ id: "is", value: "iceland", label: "Iceland", continent: "Europe" },
	{ id: "in", value: "india", label: "India", continent: "Asia" },
	{ id: "id", value: "indonesia", label: "Indonesia", continent: "Asia" },
	{ id: "ir", value: "iran", label: "Iran", continent: "Asia" },
	{ id: "iq", value: "iraq", label: "Iraq", continent: "Asia" },
	{ id: "ie", value: "ireland", label: "Ireland", continent: "Europe" },
	{ id: "il", value: "israel", label: "Israel", continent: "Asia" },
	{ id: "it", value: "italy", label: "Italy", continent: "Europe" },
	{
		id: "jm",
		value: "jamaica",
		label: "Jamaica",
		continent: "North America",
	},
	{ id: "jp", value: "japan", label: "Japan", continent: "Asia" },
	{ id: "jo", value: "jordan", label: "Jordan", continent: "Asia" },
	{ id: "kz", value: "kazakhstan", label: "Kazakhstan", continent: "Asia" },
	{ id: "ke", value: "kenya", label: "Kenya", continent: "Africa" },
	{ id: "kw", value: "kuwait", label: "Kuwait", continent: "Asia" },
	{ id: "kg", value: "kyrgyzstan", label: "Kyrgyzstan", continent: "Asia" },
	{ id: "la", value: "laos", label: "Laos", continent: "Asia" },
	{ id: "lv", value: "latvia", label: "Latvia", continent: "Europe" },
	{ id: "lb", value: "lebanon", label: "Lebanon", continent: "Asia" },
	{ id: "ls", value: "lesotho", label: "Lesotho", continent: "Africa" },
	{ id: "lr", value: "liberia", label: "Liberia", continent: "Africa" },
	{ id: "ly", value: "libya", label: "Libya", continent: "Africa" },
	{
		id: "li",
		value: "liechtenstein",
		label: "Liechtenstein",
		continent: "Europe",
	},
	{ id: "lt", value: "lithuania", label: "Lithuania", continent: "Europe" },
	{ id: "lu", value: "luxembourg", label: "Luxembourg", continent: "Europe" },
	{ id: "mg", value: "madagascar", label: "Madagascar", continent: "Africa" },
	{ id: "mw", value: "malawi", label: "Malawi", continent: "Africa" },
	{ id: "my", value: "malaysia", label: "Malaysia", continent: "Asia" },
	{ id: "mv", value: "maldives", label: "Maldives", continent: "Asia" },
	{ id: "ml", value: "mali", label: "Mali", continent: "Africa" },
	{ id: "mt", value: "malta", label: "Malta", continent: "Europe" },
	{
		id: "mh",
		value: "marshall-islands",
		label: "Marshall Islands",
		continent: "Oceania",
	},
	{ id: "mr", value: "mauritania", label: "Mauritania", continent: "Africa" },
	{ id: "mu", value: "mauritius", label: "Mauritius", continent: "Africa" },
	{ id: "mx", value: "mexico", label: "Mexico", continent: "North America" },
	{
		id: "fm",
		value: "micronesia",
		label: "Micronesia",
		continent: "Oceania",
	},
	{ id: "md", value: "moldova", label: "Moldova", continent: "Europe" },
	{ id: "mc", value: "monaco", label: "Monaco", continent: "Europe" },
	{ id: "mn", value: "mongolia", label: "Mongolia", continent: "Asia" },
	{ id: "me", value: "montenegro", label: "Montenegro", continent: "Europe" },
	{ id: "ma", value: "morocco", label: "Morocco", continent: "Africa" },
	{ id: "mz", value: "mozambique", label: "Mozambique", continent: "Africa" },
	{ id: "mm", value: "myanmar", label: "Myanmar", continent: "Asia" },
	{ id: "na", value: "namibia", label: "Namibia", continent: "Africa" },
	{ id: "nr", value: "nauru", label: "Nauru", continent: "Oceania" },
	{ id: "np", value: "nepal", label: "Nepal", continent: "Asia" },
	{
		id: "nl",
		value: "netherlands",
		label: "Netherlands",
		continent: "Europe",
	},
	{
		id: "nz",
		value: "new-zealand",
		label: "New Zealand",
		continent: "Oceania",
	},
	{
		id: "ni",
		value: "nicaragua",
		label: "Nicaragua",
		continent: "North America",
	},
	{ id: "ne", value: "niger", label: "Niger", continent: "Africa" },
	{ id: "ng", value: "nigeria", label: "Nigeria", continent: "Africa" },
	{ id: "kp", value: "north-korea", label: "North Korea", continent: "Asia" },
	{
		id: "mk",
		value: "north-macedonia",
		label: "North Macedonia",
		continent: "Europe",
	},
	{ id: "no", value: "norway", label: "Norway", continent: "Europe" },
	{ id: "om", value: "oman", label: "Oman", continent: "Asia" },
	{ id: "pk", value: "pakistan", label: "Pakistan", continent: "Asia" },
	{ id: "pw", value: "palau", label: "Palau", continent: "Oceania" },
	{ id: "ps", value: "palestine", label: "Palestine", continent: "Asia" },
	{ id: "pa", value: "panama", label: "Panama", continent: "North America" },
	{
		id: "pg",
		value: "papua-new-guinea",
		label: "Papua New Guinea",
		continent: "Oceania",
	},
	{
		id: "py",
		value: "paraguay",
		label: "Paraguay",
		continent: "South America",
	},
	{ id: "pe", value: "peru", label: "Peru", continent: "South America" },
	{ id: "ph", value: "philippines", label: "Philippines", continent: "Asia" },
	{ id: "pl", value: "poland", label: "Poland", continent: "Europe" },
	{ id: "pt", value: "portugal", label: "Portugal", continent: "Europe" },
	{ id: "qa", value: "qatar", label: "Qatar", continent: "Asia" },
	{ id: "ro", value: "romania", label: "Romania", continent: "Europe" },
	{ id: "ru", value: "russia", label: "Russia", continent: "Europe" },
	{ id: "rw", value: "rwanda", label: "Rwanda", continent: "Africa" },
	{ id: "ws", value: "samoa", label: "Samoa", continent: "Oceania" },
	{ id: "sm", value: "san-marino", label: "San Marino", continent: "Europe" },
	{
		id: "sa",
		value: "saudi-arabia",
		label: "Saudi Arabia",
		continent: "Asia",
	},
	{ id: "sn", value: "senegal", label: "Senegal", continent: "Africa" },
	{ id: "rs", value: "serbia", label: "Serbia", continent: "Europe" },
	{ id: "sc", value: "seychelles", label: "Seychelles", continent: "Africa" },
	{
		id: "sl",
		value: "sierra-leone",
		label: "Sierra Leone",
		continent: "Africa",
	},
	{ id: "sg", value: "singapore", label: "Singapore", continent: "Asia" },
	{ id: "sk", value: "slovakia", label: "Slovakia", continent: "Europe" },
	{ id: "si", value: "slovenia", label: "Slovenia", continent: "Europe" },
	{
		id: "sb",
		value: "solomon-islands",
		label: "Solomon Islands",
		continent: "Oceania",
	},
	{ id: "so", value: "somalia", label: "Somalia", continent: "Africa" },
	{
		id: "za",
		value: "south-africa",
		label: "South Africa",
		continent: "Africa",
	},
	{ id: "kr", value: "south-korea", label: "South Korea", continent: "Asia" },
	{
		id: "ss",
		value: "south-sudan",
		label: "South Sudan",
		continent: "Africa",
	},
	{ id: "es", value: "spain", label: "Spain", continent: "Europe" },
	{ id: "lk", value: "sri-lanka", label: "Sri Lanka", continent: "Asia" },
	{ id: "sd", value: "sudan", label: "Sudan", continent: "Africa" },
	{
		id: "sr",
		value: "suriname",
		label: "Suriname",
		continent: "South America",
	},
	{ id: "se", value: "sweden", label: "Sweden", continent: "Europe" },
	{
		id: "ch",
		value: "switzerland",
		label: "Switzerland",
		continent: "Europe",
	},
	{ id: "sy", value: "syria", label: "Syria", continent: "Asia" },
	{ id: "tw", value: "taiwan", label: "Taiwan", continent: "Asia" },
	{ id: "tj", value: "tajikistan", label: "Tajikistan", continent: "Asia" },
	{ id: "tz", value: "tanzania", label: "Tanzania", continent: "Africa" },
	{ id: "th", value: "thailand", label: "Thailand", continent: "Asia" },
	{ id: "tl", value: "timor-leste", label: "Timor-Leste", continent: "Asia" },
	{ id: "tg", value: "togo", label: "Togo", continent: "Africa" },
	{ id: "to", value: "tonga", label: "Tonga", continent: "Oceania" },
	{
		id: "tt",
		value: "trinidad-and-tobago",
		label: "Trinidad and Tobago",
		continent: "North America",
	},
	{ id: "tn", value: "tunisia", label: "Tunisia", continent: "Africa" },
	{ id: "tr", value: "turkey", label: "Turkey", continent: "Asia" },
	{
		id: "tm",
		value: "turkmenistan",
		label: "Turkmenistan",
		continent: "Asia",
	},
	{ id: "tv", value: "tuvalu", label: "Tuvalu", continent: "Oceania" },
	{ id: "ug", value: "uganda", label: "Uganda", continent: "Africa" },
	{ id: "ua", value: "ukraine", label: "Ukraine", continent: "Europe" },
	{
		id: "ae",
		value: "united-arab-emirates",
		label: "United Arab Emirates",
		continent: "Asia",
	},
	{
		id: "gb",
		value: "united-kingdom",
		label: "United Kingdom",
		continent: "Europe",
	},
	{
		id: "us",
		value: "united-states",
		label: "United States",
		continent: "North America",
	},
	{
		id: "uy",
		value: "uruguay",
		label: "Uruguay",
		continent: "South America",
	},
	{ id: "uz", value: "uzbekistan", label: "Uzbekistan", continent: "Asia" },
	{ id: "vu", value: "vanuatu", label: "Vanuatu", continent: "Oceania" },
	{
		id: "va",
		value: "vatican-city",
		label: "Vatican City",
		continent: "Europe",
	},
	{
		id: "ve",
		value: "venezuela",
		label: "Venezuela",
		continent: "South America",
	},
	{ id: "vn", value: "vietnam", label: "Vietnam", continent: "Asia" },
	{ id: "ye", value: "yemen", label: "Yemen", continent: "Asia" },
	{ id: "zm", value: "zambia", label: "Zambia", continent: "Africa" },
	{ id: "zw", value: "zimbabwe", label: "Zimbabwe", continent: "Africa" },
] as const satisfies Country[];
