// ISO 3661-1 alpha-2
// https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
export const iso36611Alpha2 = [
	"AF",
	"AL",
	"DZ",
	"AS",
	"AD",
	"AO",
	"AI",
	"AQ",
	"AG",
	"AR",
	"AM",
	"AW",
	"AU",
	"AT",
	"AZ",
	"BS",
	"BH",
	"BD",
	"BB",
	"BY",
	"BE",
	"BZ",
	"BJ",
	"BM",
	"BT",
	"BO",
	"BA",
	"BW",
	"BV",
	"BR",
	"IO",
	"BN",
	"BG",
	"BF",
	"BI",
	"CV",
	"KH",
	"CM",
	"CA",
	"KY",
	"CF",
	"TD",
	"CL",
	"CN",
	"CX",
	"CC",
	"CO",
	"KM",
	"CG",
	"CK",
	"CR",
	"HR",
	"CU",
	"CY",
	"CZ",
	"CI",
	"DK",
	"DJ",
	"DM",
	"DO",
	"EC",
	"EG",
	"SV",
	"GQ",
	"ER",
	"EE",
	"SZ",
	"ET",
	"FK",
	"FO",
	"FJ",
	"FI",
	"FR",
	"GF",
	"PF",
	"TF",
	"GA",
	"GM",
	"GE",
	"DE",
	"GH",
	"GI",
	"GR",
	"GL",
	"GD",
	"GP",
	"GU",
	"GT",
	"GG",
	"GN",
	"GW",
	"GY",
	"HT",
	"HM",
	"VA",
	"HN",
	"HK",
	"HU",
	"IS",
	"IN",
	"ID",
	"IR",
	"IQ",
	"IE",
	"IM",
	"IL",
	"IT",
	"JM",
	"JP",
	"JE",
	"JO",
	"KZ",
	"KE",
	"KI",
	"KP",
	"KR",
	"KW",
	"KG",
	"LA",
	"LV",
	"LB",
	"LS",
	"LR",
	"LY",
	"LI",
	"LT",
	"LU",
	"MO",
	"MG",
	"MW",
	"MY",
	"MV",
	"ML",
	"MT",
	"MH",
	"MQ",
	"MR",
	"MU",
	"YT",
	"MX",
	"FM",
	"MD",
	"MC",
	"MN",
	"ME",
	"MS",
	"MA",
	"MZ",
	"MM",
	"NA",
	"NR",
	"NP",
	"NL",
	"NC",
	"NZ",
	"NI",
	"NE",
	"NG",
	"NU",
	"NF",
	"MK",
	"NO",
	"OM",
	"PK",
	"PW",
	"PS",
	"PA",
	"PG",
	"PY",
	"PE",
	"PH",
	"PN",
	"PL",
	"PT",
	"PR",
	"QA",
	"RO",
	"RU",
	"RW",
	"RE",
	"BL",
	"SH",
	"KN",
	"LC",
	"PM",
	"VC",
	"WS",
	"SM",
	"ST",
	"SA",
	"SN",
	"RS",
	"SC",
	"SL",
	"SG",
	"SK",
	"SI",
	"SB",
	"SO",
	"ZA",
	"GS",
	"ES",
	"LK",
	"SD",
	"SR",
	"SJ",
	"SE",
	"CH",
	"SY",
	"TW",
	"TJ",
	"TZ",
	"TH",
	"TL",
	"TG",
	"TK",
	"TO",
	"TT",
	"TN",
	"TM",
	"TC",
	"TV",
	"TR",
	"UG",
	"UA",
	"AE",
	"GB",
	"US",
	"UY",
	"UZ",
	"VU",
	"VE",
	"VN",
	"VG",
	"VI",
	"WF",
	"EH",
	"YE",
	"AX",
] as const;

export type iso36611Alpha2 = (typeof iso36611Alpha2)[number];

export const iso36611Alpha2Map = {
	AF: { displayName: "Afganistán" },
	AL: { displayName: "Albania" },
	DE: { displayName: "Alemania" },
	AD: { displayName: "Andorra" },
	AO: { displayName: "Angola" },
	AI: { displayName: "Anguila" },
	AQ: { displayName: "Antártida" },
	AG: { displayName: "Antigua y Barbuda" },
	SA: { displayName: "Arabia Saudita" },
	DZ: { displayName: "Argel" },
	AR: { displayName: "Argentina" },
	AM: { displayName: "Armenia" },
	AW: { displayName: "Aruba" },
	AU: { displayName: "Australia" },
	AT: { displayName: "Austria" },
	AZ: { displayName: "Azerbaiyán" },
	BS: { displayName: "Bahamas" },
	BH: { displayName: "Bahréin" },
	BD: { displayName: "Bangladesh" },
	BB: { displayName: "Barbados" },
	BY: { displayName: "Belarús" },
	BE: { displayName: "Bélgica" },
	BZ: { displayName: "Belice" },
	BJ: { displayName: "Benin" },
	BM: { displayName: "Bermudas" },
	BT: { displayName: "Bhután" },
	BO: { displayName: "Bolivia" },
	BA: { displayName: "Bosnia y Herzegovina" },
	BW: { displayName: "Botsuana" },
	BR: { displayName: "Brasil" },
	BN: { displayName: "Brunéi" },
	BG: { displayName: "Bulgaria" },
	BF: { displayName: "Burkina Faso" },
	BI: { displayName: "Burundi" },
	CV: { displayName: "Cabo Verde" },
	KH: { displayName: "Camboya" },
	CM: { displayName: "Camerún" },
	CA: { displayName: "Canadá" },
	TD: { displayName: "Chad" },
	CL: { displayName: "Chile" },
	CN: { displayName: "China" },
	CY: { displayName: "Chipre" },
	VA: { displayName: "Ciudad del Vaticano" },
	CO: { displayName: "Colombia" },
	KM: { displayName: "Comoros" },
	CG: { displayName: "Congo" },
	KP: { displayName: "Corea del Norte" },
	KR: { displayName: "Corea del Sur" },
	CI: { displayName: "Costa de Marfil" },
	CR: { displayName: "Costa Rica" },
	HR: { displayName: "Croacia" },
	CU: { displayName: "Cuba" },
	DK: { displayName: "Dinamarca" },
	DM: { displayName: "Domínica" },
	EC: { displayName: "Ecuador" },
	EG: { displayName: "Egipto" },
	SV: { displayName: "El Salvador" },
	AE: { displayName: "Emiratos Árabes Unidos" },
	ER: { displayName: "Eritrea" },
	SK: { displayName: "Eslovaquia" },
	SI: { displayName: "Eslovenia" },
	ES: { displayName: "España" },
	US: { displayName: "Estados Unidos de América" },
	EE: { displayName: "Estonia" },
	ET: { displayName: "Etiopía" },
	FJ: { displayName: "Fiji" },
	PH: { displayName: "Filipinas" },
	FI: { displayName: "Finlandia" },
	FR: { displayName: "Francia" },
	GA: { displayName: "Gabón" },
	GM: { displayName: "Gambia" },
	GS: { displayName: "Georgia del Sur e Islas Sandwich del Sur" },
	GE: { displayName: "Georgia" },
	GH: { displayName: "Ghana" },
	GI: { displayName: "Gibraltar" },
	GD: { displayName: "Granada" },
	GR: { displayName: "Grecia" },
	GL: { displayName: "Groenlandia" },
	GP: { displayName: "Guadalupe" },
	GU: { displayName: "Guam" },
	GT: { displayName: "Guatemala" },
	GF: { displayName: "Guayana Francesa" },
	GY: { displayName: "Guayana" },
	GG: { displayName: "Guernsey" },
	GQ: { displayName: "Guinea Ecuatorial" },
	GW: { displayName: "Guinea-Bissau" },
	GN: { displayName: "Guinea" },
	HT: { displayName: "Haití" },
	HN: { displayName: "Honduras" },
	HK: { displayName: "Hong Kong" },
	HU: { displayName: "Hungría" },
	IN: { displayName: "India" },
	ID: { displayName: "Indonesia" },
	IQ: { displayName: "Irak" },
	IR: { displayName: "Irán" },
	IE: { displayName: "Irlanda" },
	BV: { displayName: "Isla Bouvet" },
	IM: { displayName: "Isla de Man" },
	IS: { displayName: "Islandia" },
	AX: { displayName: "Islas Áland" },
	KY: { displayName: "Islas Caimán" },
	CX: { displayName: "Islas Christmas" },
	CC: { displayName: "Islas Cocos" },
	CK: { displayName: "Islas Cook" },
	FO: { displayName: "Islas Faroe" },
	HM: { displayName: "Islas Heard y McDonald" },
	FK: { displayName: "Islas Malvinas" },
	MH: { displayName: "Islas Marshall" },
	NF: { displayName: "Islas Norkfolk" },
	PW: { displayName: "Islas Palaos" },
	PN: { displayName: "Islas Pitcairn" },
	SB: { displayName: "Islas Solomón" },
	SJ: { displayName: "Islas Svalbard y Jan Mayen" },
	TC: { displayName: "Islas Turcas y Caicos" },
	VG: { displayName: "Islas Vírgenes Británicas" },
	VI: { displayName: "Islas Vírgenes de los Estados Unidos de América" },
	IL: { displayName: "Israel" },
	IT: { displayName: "Italia" },
	JM: { displayName: "Jamaica" },
	JP: { displayName: "Japón" },
	JE: { displayName: "Jersey" },
	JO: { displayName: "Jordania" },
	KZ: { displayName: "Kazajstán" },
	KE: { displayName: "Kenia" },
	KG: { displayName: "Kirguistán" },
	KI: { displayName: "Kiribati" },
	KW: { displayName: "Kuwait" },
	LA: { displayName: "Laos" },
	LS: { displayName: "Lesotho" },
	LV: { displayName: "Letonia" },
	LB: { displayName: "Líbano" },
	LR: { displayName: "Liberia" },
	LY: { displayName: "Libia" },
	LI: { displayName: "Liechtenstein" },
	LT: { displayName: "Lituania" },
	LU: { displayName: "Luxemburgo" },
	MO: { displayName: "Macao" },
	MK: { displayName: "Macedonia" },
	MG: { displayName: "Madagascar" },
	MY: { displayName: "Malasia" },
	MW: { displayName: "Malawi" },
	MV: { displayName: "Maldivas" },
	ML: { displayName: "Mali" },
	MT: { displayName: "Malta" },
	MA: { displayName: "Marruecos" },
	MQ: { displayName: "Martinica" },
	MU: { displayName: "Mauricio" },
	MR: { displayName: "Mauritania" },
	YT: { displayName: "Mayotte" },
	MX: { displayName: "México" },
	FM: { displayName: "Micronesia" },
	MD: { displayName: "Moldova" },
	MC: { displayName: "Mónaco" },
	MN: { displayName: "Mongolia" },
	ME: { displayName: "Montenegro" },
	MS: { displayName: "Montserrat" },
	MZ: { displayName: "Mozambique" },
	MM: { displayName: "Myanmar" },
	NA: { displayName: "Namibia" },
	NR: { displayName: "Nauru" },
	NP: { displayName: "Nepal" },
	NI: { displayName: "Nicaragua" },
	NE: { displayName: "Níger" },
	NG: { displayName: "Nigeria" },
	NU: { displayName: "Niue" },
	NO: { displayName: "Noruega" },
	NC: { displayName: "Nueva Caledonia" },
	NZ: { displayName: "Nueva Zelanda" },
	OM: { displayName: "Omán" },
	NL: { displayName: "Países Bajos" },
	PK: { displayName: "Pakistán" },
	PS: { displayName: "Palestina" },
	PA: { displayName: "Panamá" },
	PG: { displayName: "Papúa Nueva Guinea" },
	PY: { displayName: "Paraguay" },
	PE: { displayName: "Perú" },
	PF: { displayName: "Polinesia Francesa" },
	PL: { displayName: "Polonia" },
	PT: { displayName: "Portugal" },
	PR: { displayName: "Puerto Rico" },
	QA: { displayName: "Qatar" },
	GB: { displayName: "Reino Unido" },
	CF: { displayName: "República Centro-Africana" },
	CZ: { displayName: "República Checa" },
	DO: { displayName: "República Dominicana" },
	RE: { displayName: "Reunión" },
	RW: { displayName: "Ruanda" },
	RO: { displayName: "Rumanía" },
	RU: { displayName: "Rusia" },
	EH: { displayName: "Sahara Occidental" },
	AS: { displayName: "Samoa Americana" },
	WS: { displayName: "Samoa" },
	BL: { displayName: "San Bartolomé" },
	KN: { displayName: "San Cristóbal y Nieves" },
	SM: { displayName: "San Marino" },
	PM: { displayName: "San Pedro y Miquelón" },
	VC: { displayName: "San Vicente y las Granadinas" },
	SH: { displayName: "Santa Elena" },
	LC: { displayName: "Santa Lucía" },
	ST: { displayName: "Santo Tomé y Príncipe" },
	SN: { displayName: "Senegal" },
	RS: { displayName: "Serbia y Montenegro" },
	SC: { displayName: "Seychelles" },
	SL: { displayName: "Sierra Leona" },
	SG: { displayName: "Singapur" },
	SY: { displayName: "Siria" },
	SO: { displayName: "Somalia" },
	LK: { displayName: "Sri Lanka" },
	SZ: { displayName: "Suazilandia" },
	ZA: { displayName: "Sudáfrica" },
	SD: { displayName: "Sudán" },
	SE: { displayName: "Suecia" },
	CH: { displayName: "Suiza" },
	SR: { displayName: "Surinam" },
	TH: { displayName: "Tailandia" },
	TW: { displayName: "Taiwán" },
	TZ: { displayName: "Tanzania" },
	TJ: { displayName: "Tayikistán" },
	IO: { displayName: "Territorio Británico del Océano Índico" },
	TF: { displayName: "Territorios Australes Franceses" },
	TL: { displayName: "Timor-Leste" },
	TG: { displayName: "Togo" },
	TK: { displayName: "Tokelau" },
	TO: { displayName: "Tonga" },
	TT: { displayName: "Trinidad y Tobago" },
	TN: { displayName: "Túnez" },
	TM: { displayName: "Turkmenistán" },
	TR: { displayName: "Turquía" },
	TV: { displayName: "Tuvalu" },
	UA: { displayName: "Ucrania" },
	UG: { displayName: "Uganda" },
	UY: { displayName: "Uruguay" },
	UZ: { displayName: "Uzbekistán" },
	VU: { displayName: "Vanuatu" },
	VE: { displayName: "Venezuela" },
	VN: { displayName: "Vietnam" },
	WF: { displayName: "Wallis y Futuna" },
	YE: { displayName: "Yemen" },
	DJ: { displayName: "Yibuti" },
} as const satisfies Record<iso36611Alpha2, { displayName: string }>;
