import { Wireframe } from "@ramoz/ui/components/wireframe";
import type { Metadata } from "next";
import { headers } from "next/headers";
import { cookieToInitialState } from "wagmi";
import { getConfig } from "@/wagmi-config";
import { PlaygroundNavigation } from "./playground-navigation";
import { Providers } from "./providers";

export const metadata: Metadata = {
	title: "Create Wagmi",
	description: "Generated by create-wagmi",
};

export default async function PlaygroundLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const initialState = cookieToInitialState(
		getConfig(),
		(await headers()).get("cookie")
	);
	return (
		<Wireframe
			config={{
				cssVariables: {
					"--top-nav-height": 16,
					"--bottom-nav-height": 16,
				},
			}}
		>
			<PlaygroundNavigation />
			<Providers initialState={initialState}>{children}</Providers>
		</Wireframe>
	);
}
