export const GLOBAL_TICK_PRICE = 0.25;
export const TICK_INTERVAL_MS = 5000;
export const MINIMUM_DEPOSIT_TICKS = 12;
export const TOP_UP_GRACE_PERIOD_MS = 30_000;

export const MINIMUM_STARTING_DEPOSIT =
	GLOBAL_TICK_PRICE * MINIMUM_DEPOSIT_TICKS;
