import type { Metadata } from "next";
import { headers } from "next/headers";
import type { ReactNode } from "react";
import { cookieToInitialState } from "wagmi";

import { getConfig } from "@/wagmi-config";
import { Providers } from "./pay/providers";

export const metadata: Metadata = {
	title: "Create Wagmi",
	description: "Generated by create-wagmi",
};

export default async function RootLayout(props: { children: ReactNode }) {
	const initialState = cookieToInitialState(
		getConfig(),
		(await headers()).get("cookie")
	);
	return <Providers initialState={initialState}>{props.children}</Providers>;
}
